In [1]:
import sqlite3

import pandas as pd
import numpy as np
from urllib.request import urlopen  
import json


getkey = ! cat ../../apikey.txt
apikey = getkey[0]

from fhelp import get_appended, process_datesIT

In [2]:
urls = pd.read_json('Resources/urls.json',typ='series')

In [3]:
independents = urls[[name for name in urls.index if name[0] == 'G']]
dependents = urls[[name for name in urls.index if name[0] != 'G' and name[0] != 'U']]
#dependents2 = urls[[name for name in urls.index if name[0] in 'TSEIFXC']]
unused = urls[[name for name in urls.index if name[0] == 'U']]

In [4]:
! rm ../../Finances.db
! rm schema.sql

In [5]:
urls = pd.read_json('Resources/urls.json',typ='series')

In [6]:
conn = sqlite3.connect('../../Finances.db')
c = conn.cursor()
schemas = open("schema.sql", "a+")

In [7]:
%%time
for name, url in independents.iteritems():
    print(name,url)
    tab = get_appended(url,apikey,name)
    a = pd.io.sql.get_schema(tab,name)
    c.execute('drop table if exists '+ name)
    c.execute(a)
    tosql = a +';\n\n'
    schemas.write(tosql)
    tab.to_sql(name,con=conn,index=False,if_exists='append')

G1_CV_SYMBOLS https://financialmodelingprep.com/api/v3/stock/list?apikey=
G1_CV_ETFS https://financialmodelingprep.com/api/v3/etf/list?apikey=
G1_CV_TRADABLE https://financialmodelingprep.com/api/v3/available-traded/list?apikey=
G1_CV_DELISTED https://financialmodelingprep.com/api/v3/delisted-companies?limit=1000000000&apikey=
G1_CAL_EARNINGSCALENDAR_UPC https://financialmodelingprep.com/api/v3/earning_calendar?apikey=
G1_INST_CIKLIST https://financialmodelingprep.com/api/v3/cik_list?apikey=
G1_MI_MAJORINDEXES https://financialmodelingprep.com/api/v3/quotes/index?apikey=
G1_MI_SP500LIST https://financialmodelingprep.com/api/v3/sp500_constituent?apikey=
G1_MI_SP500HIST https://financialmodelingprep.com/api/v3/historical/sp500_constituent?apikey=
G1_MI_NASDAQLIST https://financialmodelingprep.com/api/v3/nasdaq_constituent?apikey=
G1_MI_NASDAQHISTLIST https://financialmodelingprep.com/api/v3/historical/nasdaq_constituent?apikey=
G1_MI_DOWJLIST https://financialmodelingprep.com/api/v3/dowjones_constituent?apikey=
G1_MI_DOWJHISTLIST https://financialmodelingprep.com/api/v3/historical/dowjones_constituent?apikey=
G1_COM_SYMBOLS https://financialmodelingprep.com/api/v3/symbol/available-commodities?apikey=
G1_COM_PRICES https://financialmodelingprep.com/api/v3/quotes/commodity?apikey=
G1_ETF_SYMBOLS https://financialmodelingprep.com/api/v3/symbol/available-etfs?apikey=
G1_ETF_PRICES https://financialmodelingprep.com/api/v3/quotes/etf?apikey=
G1_MF_SYMBOLS https://financialmodelingprep.com/api/v3/symbol/available-mutual-funds?apikey=
G1_MF_PRICES https://financialmodelingprep.com/api/v3/quotes/mutual_fund?apikey=
CPU times: user 1.02 s, sys: 117 ms, total: 1.13 s
Wall time: 15.1 s

In [8]:
###FULL lists for full set processing
stocks = list(pd.io.sql.read_sql('select symbol from G1_CV_SYMBOLS;',con=conn).symbol)
etfs  = list(pd.io.sql.read_sql('select symbol from G1_ETF_SYMBOLS;',con=conn).symbol)
etfs2  = list(pd.io.sql.read_sql('select symbol from G1_CV_ETFS;',con=conn).symbol)
indexes = list(pd.io.sql.read_sql('select symbol from G1_MI_MAJORINDEXES;',con=conn).symbol)
ciks = [str(c) for c in list(pd.io.sql.read_sql('select cik from G1_INST_CIKLIST',con=conn).cik)]
funds = list(pd.io.sql.read_sql('select symbol from G1_MF_SYMBOLS;',con=conn).symbol)
commods = list(pd.io.sql.read_sql('select symbol from G1_COM_SYMBOLS;',con=conn).symbol)
##Light cleanup, nothing perfect –– could set this up using sql. 

#merge etf lists
etfs_c = list(set(etfs).union(set(etfs2)))
#leave stocks only 
stocks_c = list(set(stocks) - set(etfs_c + indexes + ciks + funds + commods))

#dictionary – nothing commodity, crypto, etc. specific
d = {'H':stocks_c + etfs_c + commods + funds,
     'P':stocks_c + etfs + funds,
     'T':stocks_c + etfs_c,
     'S':stocks_c,
     'E':etfs_c,
     'C':commods,
     'F':ciks,
     'I':indexes,
     'M':funds}

In [9]:
#d = {'H':stocks_sub + etfs_sub + commods + funds,'T':stocks_sub + etfs_c + commods,'S':stocks_c,'E':etfs_c,'C':ciks,'I':indexes}

In [ ]:
def get_subset(num_stocks,tickerset,apikey,commod = None,countries=None,num_indexes = 3:
    """Get sample of full dataset
    Parameters:
    num_stocks - number of stocks to choose
    tickerset - set of tickers to sample from
    commod - list of commodities to include
    country – list of two letter abbreviation of countries to sample. None for all countries
    """
    
    if num_indexes = 3:
        indexes = ['^IXIC','^GSPC','^DJI']
    #determine pool sizes, etc.
    num_etfs = int(np.ceil(num_stocks/10))
    STOCKPOOL_SIZE = num_stocks * 10
    ETFPOOL_SIZE = num_etfs * 10
    
    global dependents
    
    #get profile of etfs and stocks
    profile = get_appended(dependents['P1b1000_CV_PROFILE'],apikey,'P1b1000_CV_PROFILE',tickers = tickerset)
    if countries:
        profile = profile[profile.country.isin(countries)]
    stockpool = list(profile[profile.isEtf == False].sort_values(by='volAvg',ascending=False)[:STOCKPOOL_SIZE].symbol)
    etfpool = list(profile[profile.isEtf == True].sort_values(by='volAvg',ascending=False)[:ETFPOOL_SIZE].symbol)
    stocks = np.random.choice(stockpool,num_stocks)
    etfs = np.random.choice(etfpool,num_etfs)
    tickers = atocks + etfs
    if commod:
        tickers += commod
    
    #related mutual fund data
    funds = get_appended(dependents['T1_INST_MUTFUNDHOLDERS'],apikey,'T1_INST_MUTFUNDHOLDERS',tickers=tickers)
    funds = list(fundtable.symbol.value_counts().index)

In [11]:
num_stocks = 100
commod = False
countries = ['US']
num_indexes = 3

In [13]:
if num_indexes = 3:
num_etfs = int(np.ceil(num_stocks/10))
STOCKPOOL_SIZE = num_stocks * 10
ETFPOOL_SIZE = num_etfs * 10

#get profile of etfs and stocks
profile = get_appended(dependents['P1b1000_CV_PROFILE'],apikey,'P1b1000_CV_PROFILE',tickers = stocks_c + etfs_c)
if countries: #refine to subset of countries parameter
    profile = profile[profile.country.isin(countries)]
#select subset of stocks from pool 
stockpool = list(profile[profile.isEtf == False].sort_values(by='volAvg',ascending=False)[:STOCKPOOL_SIZE].symbol)
etfpool = list(profile[profile.isEtf == True].sort_values(by='volAvg',ascending=False)[:ETFPOOL_SIZE].symbol)
stocks = list(np.random.choice(stockpool,num_stocks))
etfs = list(np.random.choice(etfpool,num_etfs))
tickers = stocks + etfs
if commod:
    tickers += commod

In [18]:
%%time
#Retrieve list of funds that hold symbols in sampled list 
fundtable = get_appended(dependents['T1_INST_MUTFUNDHOLDERS'],apikey,'T1_INST_MUTFUNDHOLDERS',tickers=tickers)
funds = list(fundtable.symbol.value_counts().index)

CPU times: user 2.3 s, sys: 108 ms, total: 2.41 s
Wall time: 45 s

In [ ]:
#choose indexes

In [142]:
tempdf = pd.DataFrame()
for i in range(len(jsony)):
    jsonx = pd.DataFrame(jsony.iloc[i,0])
    symbname = jsonx.columns[0]
    df = jsonx.iloc[:,1].apply(lambda x: pd.Series(x))
    df[symbname] = jsonx.loc[0,symbname]
    tempdf = tempdf.append((df))

In [144]:
tempdf

,date,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime,symbol
0,2021-02-26,2029.949951,2056.520020,2001.010010,2021.910034,2021.910034,2001500.0,2001500.0,-8.03992,-0.396,2026.48002,"February 26, 21",-0.00396,GOOGL
1,2021-02-25,2055.929932,2083.000000,2006.489990,2015.949951,2015.949951,2077400.0,2077400.0,-39.97998,-1.945,2035.14665,"February 25, 21",-0.01945,GOOGL
2,2021-02-24,2030.040039,2088.320068,2027.530029,2083.810059,2083.810059,1130400.0,1130400.0,53.77002,2.649,2066.55339,"February 24, 21",0.02649,GOOGL
3,2021-02-23,2013.989990,2072.500000,1990.229980,2060.120117,2060.120117,1732900.0,1732900.0,46.13013,2.290,2040.95003,"February 23, 21",0.02290,GOOGL
4,2021-02-22,2053.600098,2080.330078,2048.000000,2054.260010,2054.260010,1473300.0,1473300.0,0.65991,0.032,2060.86336,"February 22, 21",0.00032,GOOGL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2016-03-04,13.560000,13.860000,13.430000,13.590000,10.650319,31818600.0,31818600.0,0.03000,0.221,13.62667,"March 04, 16",0.00221,F
1255,2016-03-03,13.250000,13.610000,13.240000,13.540000,10.611133,44524500.0,44524500.0,0.29000,2.189,13.46333,"March 03, 16",0.02189,F
1256,2016-03-02,13.060000,13.350000,13.040000,13.220000,10.360353,36598200.0,36598200.0,0.16000,1.225,13.20333,"March 02, 16",0.01225,F
1257,2016-03-01,13.010000,13.120000,12.720000,13.090000,10.258475,71523900.0,71523900.0,0.08000,0.615,12.97667,"March 01, 16",0.00615,F
1258,2016-02-29,12.420000,12.650000,12.390000,12.510000,9.803936,32999100.0,32999100.0,0.09000,0.725,12.51667,"February 29, 16",0.00725,F

def get_dependents():
    global dependents
    for name, url in dependents.iteritems():
        symbols = d.get(name[0])
        tab = get_appended(url,apikey,symbols,json=name[1],verbose=True)
        a = pd.io.sql.get_schema(tab,name)
        c.execute('drop table if exists '+ name)
        c.execute(a)
        tosql = a +';\n\n'
        schemas.write(tosql)
        tab.to_sql(name,con=conn,index=False,if_exists='append')