In [1]:
import sqlite3

import pandas as pd
import numpy as np
from urllib.request import urlopen  
import json

getkey = ! cat ../../apikey.txt
apikey = getkey[0]

from Resources.fhelp import get_appended, get_appended2

In [2]:
#get list of tickers (just dow until everything is set up)
dow_url = "https://financialmodelingprep.com/api/v3/dowjones_constituent?apikey=600e501fe324b2f1cbb2aec5b390b6db"
dow_tick = pd.read_json(dow_url)
tickers = list(dow_tick.symbol.values)
print(tickers,)
tickers += ['SECO']

['CRM', 'WBA', 'V', 'NKE', 'UNH', 'TRV', 'VZ', 'INTC', 'WMT', 'JNJ', 'DIS', 'MCD', 'JPM', 'CAT', 'BA', 'AMGN', 'DOW', 'AAPL', 'GS', 'CSCO', 'MSFT', 'HD', 'PG', 'MRK', 'IBM', 'HON', 'KO', 'CVX', 'AXP', 'MMM']

In [3]:
urls = pd.read_json('Resources/urls.json',typ='series')

In [4]:
conn = sqlite3.connect('../../Finances.db')
c = conn.cursor()

In [5]:
tickers = ['AAPL']

In [7]:
schemas = open("schema.sql", "a+")
for name, url in zip(urls.index,urls.values):
    print(name)
    if url =='NONE':
            continue
    if type(url) != dict:
        tab = get_appended2(url,tickers,apikey,verbose=False)
        tab.drop_duplicates(inplace=True)
        a = pd.io.sql.get_schema(tab,name)
        c.execute('drop table if exists '+ name)
        c.execute(a)
        tosql = a +';\n\n'
        schemas.write(tosql)
        tab.to_sql(name,con=conn,index=False,if_exists='append')
    else: 
        for i, u in enumerate(url.values()):
            print(u)
            if i == 1: 
                tab = get_appended2(u,tickers,apikey,verbose=True)
                tab.drop_duplicates(inplace=True)
                a = pd.io.sql.get_schema(tab,name)
                c.execute('drop table if exists '+ name)
                c.execute(a)
                tosql = a +';\n\n'
                schemas.write(tosql)
                tab.to_sql(name,con=conn,index=False,if_exists='append')
                print(c.execute('select * from '+name+' limit 1;').fetchall())
            else:
                tab= get_appended2(u,tickers,apikey,verbose=True)
                tab.drop_duplicates(inplace=True)
                tab.to_sql(name,con=conn,index=False,if_exists='append')

CV_PROFILE
CV_QUOTE
CV_EXECUTIVES
NAMER-------------
AAPL
CV_SEARCH
CV_FS_INCOME_YR
CV_FS_INCOME_QTR
CV_FS_BALANCESHEET_YR
CV_FS_BALANCESHEET_QTR
CV_FS_CASHFLOW_YR
CV_FS_CASHFLOW_QTR
CV_FS_INCOMEGROWTH_YR
CV_FS_BALANCEGROWTH_YR
CV_FS_CASHGROWTH_YR
CV_INTLFILINGS
CV_FS_ASREPORTED
CV_RATIOS_TTM
NAMER-------------
AAPL
CV_RATIOS_YR
CV_RATIOS_QTR
CV_ENTERPRISEVALUE_YR
CV_ENTERPRISEVALUE_QTR
CV_METRICS_TTM
NAMER-------------
AAPL
CV_METRICS_YR
CV_METRICS_QTR
CV_GROWTH_YR
CV_GROWTH_QTR
CV_RATING
CV_RATING_DAY
CV_DCF

/Users/verbeck/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  if __name__ == '__main__':
/Users/verbeck/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:2663: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  method=method,

CV_DCF_YR
IGASKJB AAPL
NAMER-------------
AAPL
CV_DCF_QTR
IGASKJB AAPL
NAMER-------------
AAPL
CV_DCF_DAY
CV_MARKETCAP
CV_MARKETCAP_DAY
CV_SYMBOLS
CV_ETFS
CV_TRADABLE
CV_BATCHREQUEST
CV_STOCKSCREENER
CV_DELISTED
CV_NEWS
CV_EARNINGSCALLTRANSCRIPT
CV_EARNINGSSURPRISES
CV_SECFILINGS
C_PRESSRELEASES
INS_STOCKTRADING
INS_RSSFEED
CAL_EARNINGSCALENDAR_UPC
CAL_EARNINGSCALENDAR_HIST
CAL_IPO
CAL_SPLITS
CAL_DIVIDENDS
CAL_ECONOMIC
INST_HOLDERS
NAMER-------------
AAPL
INST_MUTFUNDHOLDERS
NAMER-------------
AAPL
INST_ETFHOLDERS
NAMER-------------
AAPL
INST_ETFSECTORWEIGHTS
NAMER-------------
AAPL
INST_ETFCOUNTRYWEIGHTS
NAMER-------------
AAPL
INST_SECRSSFEED
INST_13F
TS_PRICE
TS_PRICELIST
TS_PRICE_DAY
UYJFDKJB AAPL
NAMER-------------
AAPL
TS_DIVIDENDS_HIST
UYJFDKJB AAPL
NAMER-------------
AAPL
TS_SPLITS_HIST
UYJFDKJB AAPL
NAMER-------------
AAPL
TS_BIASFREE
TI_DAILY
TI_INTRADAY
MI_MAJORINDEXES
MI_SP500LIST
MI_SP500HIST
MI_NASDAQLIST
MI_NASDAQHISTLIST
MI_DOWJLIST
MI_DOWJHISTLIST
MI_INDEXPRICEHIST_DAY
https://financialmodelingprep.com/api/v3/historical-price-full/%5EGSPC?apikey=
Downloading for ticker AAPL....
UYJFDKJB ^GSPC
NAMER-------------
^GSPC

,date,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime,symbol
0,2021-02-12,3911.649902,3937.229980,3905.780029,3934.830078,3934.830078,4.119260e+09,4.119260e+09,23.18018,0.593,3925.94670,"February 12, 21",0.00593,^GSPC
1,2021-02-11,3916.399902,3925.989990,3890.389893,3916.379883,3916.379883,4.570080e+09,4.570080e+09,-0.02002,-0.001,3910.91992,"February 11, 21",-0.00001,^GSPC
2,2021-02-10,3920.780029,3931.500000,3884.939941,3909.879883,3909.879883,4.815380e+09,4.815380e+09,-10.90015,-0.278,3908.77327,"February 10, 21",-0.00278,^GSPC
3,2021-02-09,3910.489990,3918.350098,3902.639893,3911.229980,3911.229980,4.554610e+09,4.554610e+09,0.73999,0.019,3910.73999,"February 09, 21",0.00019,^GSPC
4,2021-02-08,3892.590088,3915.770020,3892.590088,3915.590088,3915.590088,4.635030e+09,4.635030e+09,23.00000,0.591,3907.98340,"February 08, 21",0.00591,^GSPC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2016-02-22,1924.439941,1946.699951,1924.439941,1945.500000,1945.500000,4.054710e+09,4.054710e+09,21.06006,1.094,1938.87996,"February 22, 16",0.01094,^GSPC
1255,2016-02-19,1916.739990,1918.780029,1902.170044,1917.780029,1917.780029,4.142850e+09,4.142850e+09,1.04004,0.054,1912.91003,"February 19, 16",0.00054,^GSPC
1256,2016-02-18,1927.569946,1930.000000,1915.089966,1917.829956,1917.829956,4.436490e+09,4.436490e+09,-9.73999,-0.505,1920.97331,"February 18, 16",-0.00505,^GSPC
1257,2016-02-17,1898.800049,1930.680054,1898.800049,1926.819946,1926.819946,5.011540e+09,5.011540e+09,28.01990,1.476,1918.76668,"February 17, 16",0.01476,^GSPC
1258,2016-02-16,1871.439941,1895.770020,1871.439941,1895.579956,1895.579956,4.570670e+09,4.570670e+09,24.14001,1.290,1887.59664,"February 16, 16",0.01290,^GSPC

https://financialmodelingprep.com/api/v3/historical-price-full/%5EIXIC?apikey=
Downloading for ticker AAPL....
UYJFDKJB ^IXIC
NAMER-------------
^IXIC

,date,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime,symbol
0,2021-02-12,13979.209961,14102.040039,13937.709961,14095.469727,14095.469727,7.352960e+09,7.352960e+09,116.25977,0.832,14045.07324,"February 12, 21",0.00832,^IXIC
1,2021-02-11,14045.209961,14058.910156,13916.849609,14025.769531,14025.769531,1.000020e+10,1.000020e+10,-19.44043,-0.138,14000.50977,"February 11, 21",-0.00138,^IXIC
2,2021-02-10,14093.349609,14109.120117,13845.469727,13972.530273,13972.530273,1.016555e+10,1.016555e+10,-120.81934,-0.857,13975.70671,"February 10, 21",-0.00857,^IXIC
3,2021-02-09,13966.820313,14044.950195,13966.549805,14007.700195,14007.700195,8.658980e+09,8.658980e+09,40.87988,0.293,14006.40007,"February 09, 21",0.00293,^IXIC
4,2021-02-08,13937.059570,13987.740234,13894.150391,13987.639648,13987.639648,8.439940e+09,8.439940e+09,50.58008,0.363,13956.51009,"February 08, 21",0.00363,^IXIC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2016-02-22,4548.310059,4576.470215,4546.549805,4570.609863,4570.609863,1.794020e+09,1.794020e+09,22.29980,0.490,4564.54329,"February 22, 16",0.00490,^IXIC
1255,2016-02-19,4464.669922,4513.149902,4455.100098,4504.430176,4504.430176,1.903770e+09,1.903770e+09,39.76025,0.891,4490.89339,"February 19, 16",0.00891,^IXIC
1256,2016-02-18,4548.100098,4548.470215,4482.770020,4487.540039,4487.540039,1.955870e+09,1.955870e+09,-60.56006,-1.332,4506.26009,"February 18, 16",-0.01332,^IXIC
1257,2016-02-17,4471.660156,4540.779785,4463.509766,4534.060059,4534.060059,2.296440e+09,2.296440e+09,62.39990,1.395,4512.78320,"February 17, 16",0.01395,^IXIC
1258,2016-02-16,4397.950195,4435.959961,4376.520020,4435.959961,4435.959961,2.117920e+09,2.117920e+09,38.00977,0.864,4416.14665,"February 16, 16",0.00864,^IXIC

[('2021-02-12', 13979.209961, 14102.040039, 13937.709961, 14095.469727, 14095.469727, 7352960000.0, 7352960000.0, 116.25977, 0.8320000000000001, 14045.07324, 'February 12, 21', 0.008320000000000001, '^IXIC')]
https://financialmodelingprep.com/api/v3/historical-price-full/%5EDJI?apikey=
Downloading for ticker AAPL....
UYJFDKJB ^DJI
NAMER-------------
^DJI

,date,open,high,low,close,adjClose,volume,unadjustedVolume,change,changePercent,vwap,label,changeOverTime,symbol
0,2021-02-12,31420.800781,31475.310547,31347.800781,31458.400391,31458.400391,2630900.0,2630900.0,37.59961,0.120,31427.17057,"February 12, 21",0.00120,^DJI
1,2021-02-11,31466.490234,31543.820313,31244.359375,31430.699219,31430.699219,2803200.0,2803200.0,-35.79102,-0.114,31406.29297,"February 11, 21",-0.00114,^DJI
2,2021-02-10,31428.019531,31511.439453,31221.320313,31437.800781,31437.800781,3264500.0,3264500.0,9.78125,0.031,31390.18685,"February 10, 21",0.00031,^DJI
3,2021-02-09,31359.880859,31439.470703,31245.859375,31375.830078,31375.830078,3082100.0,3082100.0,15.94922,0.051,31353.72005,"February 09, 21",0.00051,^DJI
4,2021-02-08,31191.199219,31386.099609,31191.199219,31385.759766,31385.759766,3222500.0,3222500.0,194.56055,0.624,31321.01953,"February 08, 21",0.00624,^DJI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2016-02-22,16417.130859,16664.240234,16417.130859,16620.660156,16620.660156,102240000.0,102240000.0,203.52930,1.240,16567.34375,"February 22, 16",0.01240,^DJI
1255,2016-02-19,16410.960938,16410.960938,16278.000000,16391.990234,16391.990234,134340000.0,134340000.0,-18.97070,-0.116,16360.31706,"February 19, 16",-0.00116,^DJI
1256,2016-02-18,16483.759766,16511.839844,16390.429688,16413.429688,16413.429688,104950000.0,104950000.0,-70.33008,-0.427,16438.56641,"February 18, 16",-0.00427,^DJI
1257,2016-02-17,16217.980469,16486.119141,16217.980469,16453.830078,16453.830078,124080000.0,124080000.0,235.84961,1.454,16385.97656,"February 17, 16",0.01454,^DJI
1258,2016-02-16,16012.389648,16196.410156,16012.389648,16196.410156,16196.410156,142030000.0,142030000.0,184.02051,1.149,16135.06999,"February 16, 16",0.01149,^DJI

'CREATE TABLE "CV_EXECUTIVES" (\n\n)'

In [ ]:
u = urls['TS_PRICE_DAY']
uu = u.replace(' ','AAPL') + apikey
output = json.load(urlopen(uu))
norm = pd.read_json(uu)
display(norm)
norm.shape

In [ ]:
ttdf =  pd.DataFrame()
for i in range(len(norm)):
    ttdf = ttdf.append(pd.Series(norm.iloc[i,1]),ignore_index=True)

In [23]:
norm.loc[:,'Series'] = pd.Series(norm.iloc[:,1])

In [33]:
ser = pd.Series(norm.iloc[:,1])

In [46]:
u = urls['TS_PRICE_DAY']
uu = u.replace(' ','AAPL') + apikey
output = json.load(urlopen(uu))
norm = pd.read_json(uu)

In [ ]:
pd.read_json(json.dumps(pd.read_json(uu).iloc[0,1]))

In [ ]:
ttdf = pd.read_json(uu)
print(ttdf)
            
if ttdf.shape == (1,2):
    print(ttdf)
    ttdf = pd.read_json(json.dumps(pd.read_json(uu).iloc[0,1]))
    print(ttdf)

In [43]:
norm['historical'] = norm['historical'].apply(lambda x: pd.Series(x))

In [7]:
indexp = urls['MI_INDEXPRICEHIST_DAY']

In [8]:
for i in indexp:
    print(pd.read_json(indexp[i]))

ValueError: If using all scalar values, you must pass an index

In [9]:
pd.read_json(indexp[i]+apikey)

     symbol                                         historical
0     ^GSPC  {'date': '2021-02-12', 'open': 3911.649902, 'h...
1     ^GSPC  {'date': '2021-02-11', 'open': 3916.399902, 'h...
2     ^GSPC  {'date': '2021-02-10', 'open': 3920.780029, 'h...
3     ^GSPC  {'date': '2021-02-09', 'open': 3910.48999, 'hi...
4     ^GSPC  {'date': '2021-02-08', 'open': 3892.590088, 'h...
...     ...                                                ...
1254  ^GSPC  {'date': '2016-02-22', 'open': 1924.439941, 'h...
1255  ^GSPC  {'date': '2016-02-19', 'open': 1916.73999, 'hi...
1256  ^GSPC  {'date': '2016-02-18', 'open': 1927.569946, 'h...
1257  ^GSPC  {'date': '2016-02-17', 'open': 1898.800049, 'h...
1258  ^GSPC  {'date': '2016-02-16', 'open': 1871.439941, 'h...

[1259 rows x 2 columns]

In [10]:
pd.DataFrame(indexp).iloc[0:,] + apikey

ValueError: If using all scalar values, you must pass an index

In [12]:
a2 = pd.DataFrame()
a = pd.Series(data=indexp)
for i in range(3):
    print(a.iloc[i]+apikey)
    try:
        print(pd.read_json(a.iloc[i]+apikey))
    except Exception as e:
        print('Failed')

https://financialmodelingprep.com/api/v3/historical-price-full/%5EGSPC?apikey=600e501fe324b2f1cbb2aec5b390b6db
     symbol                                         historical
0     ^GSPC  {'date': '2021-02-12', 'open': 3911.649902, 'h...
1     ^GSPC  {'date': '2021-02-11', 'open': 3916.399902, 'h...
2     ^GSPC  {'date': '2021-02-10', 'open': 3920.780029, 'h...
3     ^GSPC  {'date': '2021-02-09', 'open': 3910.48999, 'hi...
4     ^GSPC  {'date': '2021-02-08', 'open': 3892.590088, 'h...
...     ...                                                ...
1254  ^GSPC  {'date': '2016-02-22', 'open': 1924.439941, 'h...
1255  ^GSPC  {'date': '2016-02-19', 'open': 1916.73999, 'hi...
1256  ^GSPC  {'date': '2016-02-18', 'open': 1927.569946, 'h...
1257  ^GSPC  {'date': '2016-02-17', 'open': 1898.800049, 'h...
1258  ^GSPC  {'date': '2016-02-16', 'open': 1871.439941, 'h...

[1259 rows x 2 columns]
https://financialmodelingprep.com/api/v3/historical-price-full/%5EIXIC?apikey=600e501fe324b2f1cbb2aec5b390b6db
     symbol                                         historical
0     ^IXIC  {'date': '2021-02-12', 'open': 13979.209961, '...
1     ^IXIC  {'date': '2021-02-11', 'open': 14045.209961, '...
2     ^IXIC  {'date': '2021-02-10', 'open': 14093.349609, '...
3     ^IXIC  {'date': '2021-02-09', 'open': 13966.820313, '...
4     ^IXIC  {'date': '2021-02-08', 'open': 13937.05957, 'h...
...     ...                                                ...
1254  ^IXIC  {'date': '2016-02-22', 'open': 4548.310059, 'h...
1255  ^IXIC  {'date': '2016-02-19', 'open': 4464.669922, 'h...
1256  ^IXIC  {'date': '2016-02-18', 'open': 4548.100098, 'h...
1257  ^IXIC  {'date': '2016-02-17', 'open': 4471.660156, 'h...
1258  ^IXIC  {'date': '2016-02-16', 'open': 4397.950195, 'h...

[1259 rows x 2 columns]
https://financialmodelingprep.com/api/v3/historical-price-full/%5DJI?apikey=600e501fe324b2f1cbb2aec5b390b6db
Empty DataFrame
Columns: []
Index: []